---
- name: Download RHEL QCOW2 images to the default libvirt storage location
  ansible.builtin.include_role:
    name: rhsm_download
  vars:
    rhsm_download_directory: "{{ lab_host_image_path }}"
    rhsm_download_files:
      - "{{ vm.image }}"
  loop: "{{ lab.hosts }}"
  loop_control:
    loop_var: vm
...
