---
- name: Print information about host
  ansible.builtin.debug:
    msg: "Going to create host {{ item.name }} with a {{ item.disksize | default('10') }} disk image, {{ item.cpu | default('1') }} cpu(s) and {{ item.memory | default('2048') }} memory"

- name: Check if guest is already defined "{{ item.name }}"
  community.libvirt.virt:
    command: info
  register: lab_virt_info

- name: Create a host based on a RHEL image
  include_tasks: rhel_host.yml
  when:
    - ( item.image is not defined or item.image != "blank" )
    - item.name not in lab_virt_info

- name: Create a blank host
  include_tasks: blank_host.yml
  when:
    - item.image == "blank"
    - item.name not in lab_virt_info

- name: Add a static DHCP entry for host {{ item.name }}
  community.libvirt.virt_net:
    name: "{{ lab.network.name }}"
    command: modify
    xml: "<host mac='{{ item.macaddr }}' name='my_vm' ip='{{ item.ipaddr }}'/>"

- name: Enable autostart for host {{ item.name }}
  community.libvirt.virt:
    autostart: yes
    name: "{{ item.name }}"

- name: Restart host if required
  block:
    - name: shutdown host {{ item.name }}
      community.libvirt.virt:
        state: shutdown
        name: "{{ item.name }}"

    - name: Give host time to shut down
      pause:
        seconds: 10

    - name: Start host {{ item.name }}
      community.libvirt.virt:
        state: running
        name: "{{ item.name }}"
  when:
    - item.name in lab_virt_info
    - lab_recreate_network|bool

- name: Add additional disks to guest
  include_tasks: add_disk.yml
  loop: "{{ item.additional_disks }}"
  loop_control:
    loop_var: disk
  when: item.additional_disks is defined
