---
# - name: Check if variables are valid
#   ansible.builtin.fail:
#   when:

- name: Get the current User ID
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - 'user_id'

- name: Set the path to images
  set_fact:
    lab_host_image_path: "{{ lab_user_image_path if ansible_facts.user_id != 'root' | default(lab_image_path) }}"

- name: Creating new lab environement {{ lab.name }}
  when:
    - not lab_destroy|bool
  block:
    - name: Download required images
      ansible.builtin.include_tasks:
        file: download_image.yaml

    - name: Creating network
      ansible.builtin.include_tasks:
        file: network.yml
      when:
        - lab.network is defined
        - lab.network.type == "nat"

    - name: Creating lab hosts
      ansible.builtin.include_tasks:
        file: host.yml
      with_items: "{{ lab.hosts }}"
      when: lab.hosts is defined

    - name: Deploy CA certificate
      ansible.builtin.include_tasks:
        ca.yml
      with_items: "{{ lab.hosts }}"
      when: lab.hosts is defined

- name: Removing lab environment {{ lab.name }}
  when:
    - lab_destroy|bool
  block:
    - name: Removing hosts
      ansible.builtin.include_tasks:
        file: remove_host.yml
      with_items: "{{ lab.hosts }}"
      when: lab.hosts is defined

    - name: Removing network
      ansible.builtin.include_tasks: remove_network.yml
      when:
        - lab.network is defined
        - lab.network.type == 'nat'
        - lab.network.name != 'default'
...
